### ISSUE TITLE
Update to rspirv 0.12

### ISSUE THREAD

**Issue by tuxerr** [Traverse-Research/rspirv-reflect#32]
Hi :) 
Using rspirv-reflect I'm unable to generate a reflection, executing:
```
        let reflect_module = Reflection::new_from_spirv(&spv_bytes.as_slice()).expect("Failure to create reflection module");
```
returns an SourceLanguageUnknown error. I'm using pretty new functionality (mesh shaders, buffer device address and pointers). Using cargo patch to manually update rspirv-reflect to rspirv version 0.12 from 0.11, it works (I just needed to change
```
Operand::LiteralInt32
```
to
```
Operand::LiteralBit32
```
). Is that something you'd consider either doing and updating on crates.io, or would consider accepting as a PR if I submit it?

Thank you :)

**Comment by MarijnS95** [comment]
Thanks for the reminder! I think I completely forgot to submit this after contributing to and testing with the latest `rspirv` release. Fixes should be pushed at #33, please test it out briefly before we make a new release :crossed_fingers:

**Comment by tuxerr** [comment]
This is exactly the code I tested locally (update to 0.12 and change the ints to bits) so I can confirm this works for me! :)
thank you for the extremely rapid response!!!

**Comment by tuxerr** [comment]
Hey @MarijnS95 , any chance of this landing any time soon? thanks!

**Comment by MarijnS95** [comment]
@tuxerr the `0.9.0` release with `rspirv 0.12` is [now available on crates.io](https://crates.io/crates/rspirv-reflect)! :tada:
